// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nobfvsdxxpfpyrypapdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vYmZ2c2R4eHBmcHlyeXBhcGR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzU4MDIsImV4cCI6MjA2MDMxMTgwMn0.N6Gtc5BImtHLYNOIzC1cQ1npW9ydLUXJF_bhrheEQSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);